In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("employee_burnout_analysis.xlsx")

In [3]:
df

Employee ID Date of Joining  Gender Company Type  \
0      fffe32003000360033003200      2008-09-30  Female      Service   
1          fffe3700360033003500      2008-11-30    Male      Service   
2      fffe31003300320037003900      2008-03-10  Female      Product   
3      fffe32003400380032003900      2008-11-03    Male      Service   
4      fffe31003900340031003600      2008-07-24  Female      Service   
...                         ...             ...     ...          ...   
22745  fffe31003500370039003100      2008-12-30  Female      Service   
22746  fffe33003000350031003800      2008-01-19  Female      Product   
22747          fffe390032003000      2008-11-05    Male      Service   
22748  fffe33003300320036003900      2008-01-10  Female      Service   
22749      fffe3400350031003800      2008-01-06    Male      Product   

      WFH Setup Available  Designation  Resource Allocation  \
0                      No            2                  3.0   
1                     Yes            1                  2.0   
2                     Yes            2                  NaN   
3                     Yes            1                  1.0   
4                      No            3                  7.0   
...                   ...          ...                  ...   
22745                  No            1                  3.0   
22746                 Yes            3                  6.0   
22747                 Yes            3                  7.0   
22748                  No            2                  5.0   
22749                  No            3                  6.0   

       Mental Fatigue Score  Burn Rate  
0                       3.8       0.16  
1                       5.0       0.36  
2                       5.8       0.49  
3                       2.6       0.20  
4                       6.9       0.52  
...                     ...        ...  
22745                   NaN       0.41  
22746                   6.7       0.59  
22747                   NaN       0.72  
22748                   5.9       0.52  
22749                   7.8       0.61  

[22750 rows x 9 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22750 entries, 0 to 22749
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   Employee ID           22750 non-null  object        
 1   Date of Joining       22750 non-null  datetime64[ns]
 2   Gender                22750 non-null  object        
 3   Company Type          22750 non-null  object        
 4   WFH Setup Available   22750 non-null  object        
 5   Designation           22750 non-null  int64         
 6   Resource Allocation   21369 non-null  float64       
 7   Mental Fatigue Score  20633 non-null  float64       
 8   Burn Rate             21626 non-null  float64       
dtypes: datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 1.6+ MB


In [5]:
df.isnull().sum()

Employee ID                0
Date of Joining            0
Gender                     0
Company Type               0
WFH Setup Available        0
Designation                0
Resource Allocation     1381
Mental Fatigue Score    2117
Burn Rate               1124
dtype: int64

In [6]:
df.drop(labels = ["Employee ID"],axis=1,inplace=True)

In [7]:
df

Date of Joining  Gender Company Type WFH Setup Available  Designation  \
0          2008-09-30  Female      Service                  No            2   
1          2008-11-30    Male      Service                 Yes            1   
2          2008-03-10  Female      Product                 Yes            2   
3          2008-11-03    Male      Service                 Yes            1   
4          2008-07-24  Female      Service                  No            3   
...               ...     ...          ...                 ...          ...   
22745      2008-12-30  Female      Service                  No            1   
22746      2008-01-19  Female      Product                 Yes            3   
22747      2008-11-05    Male      Service                 Yes            3   
22748      2008-01-10  Female      Service                  No            2   
22749      2008-01-06    Male      Product                  No            3   

       Resource Allocation  Mental Fatigue Score  Burn Rate  
0                      3.0                   3.8       0.16  
1                      2.0                   5.0       0.36  
2                      NaN                   5.8       0.49  
3                      1.0                   2.6       0.20  
4                      7.0                   6.9       0.52  
...                    ...                   ...        ...  
22745                  3.0                   NaN       0.41  
22746                  6.0                   6.7       0.59  
22747                  7.0                   NaN       0.72  
22748                  5.0                   5.9       0.52  
22749                  6.0                   7.8       0.61  

[22750 rows x 8 columns]

In [8]:
df.iloc[:,5].unique()

array([ 3.,  2., nan,  1.,  7.,  4.,  6.,  5.,  8., 10.,  9.])

In [9]:
df.iloc[:,6].unique()

array([ 3.8,  5. ,  5.8,  2.6,  6.9,  3.6,  7.9,  4.4,  nan,  5.3,  1.8,
        4.7,  5.9,  6.7,  4. ,  7.6,  6.3,  7.7,  6.6,  7.4,  3.9,  3. ,
        8.7,  7.3,  5.4,  6. ,  7.5, 10. ,  6.4,  5.1,  5.6,  6.1,  3.1,
        8. ,  6.8,  4.9,  9.2,  6.5,  6.2,  8.2,  4.1,  4.3,  0.8,  2.9,
        2. ,  9.1,  0. ,  5.7,  8.3,  5.5,  7. ,  3.3,  7.8,  7.2,  5.2,
        8.9,  4.5,  8.1,  8.6,  9.5,  3.5,  4.8,  2.4,  3.7,  1. ,  8.8,
        9.3,  4.6,  9.9,  0.5,  2.8,  9. ,  3.4,  4.2,  1.6,  2.7,  1.3,
        3.2,  8.4,  7.1,  9.4,  2.1,  9.7,  2.5,  1.9,  1.7,  9.6,  0.7,
        0.2,  1.2,  8.5,  9.8,  2.2,  1.1,  0.9,  2.3,  0.4,  1.4,  1.5,
        0.6,  0.3,  0.1])

In [10]:
df.iloc[:,7].unique()

array([0.16, 0.36, 0.49, 0.2 , 0.52, 0.29, 0.62, 0.33, 0.56, 0.67, 0.5 ,
       0.12, 0.4 , 0.51, 0.32, 0.39, 0.59, 0.22, 0.68, 0.57, 0.47, 0.46,
       0.61, 0.91, 0.44, 0.6 , 0.45, 0.19, 0.31, 0.81, 0.42, 0.53,  nan,
       0.94, 0.37, 0.65, 0.38, 0.15, 0.26, 0.28, 0.71, 0.8 , 0.63, 0.79,
       0.72, 0.34, 0.27, 0.66, 0.04, 0.05, 0.11, 0.41, 0.76, 0.43, 0.85,
       0.35, 0.  , 0.55, 0.48, 0.7 , 0.18, 0.23, 0.25, 0.75, 0.1 , 0.73,
       0.58, 0.88, 0.77, 0.3 , 0.06, 0.03, 0.69, 0.24, 0.74, 0.86, 0.92,
       0.78, 0.21, 0.98, 0.02, 0.82, 0.93, 0.83, 0.87, 0.64, 0.54, 0.17,
       1.  , 0.08, 0.09, 0.14, 0.13, 0.07, 0.84, 0.99, 0.01, 0.97, 0.95,
       0.9 , 0.96, 0.89])

In [11]:
df = df.dropna()

In [12]:
df.isnull().sum()

Date of Joining         0
Gender                  0
Company Type            0
WFH Setup Available     0
Designation             0
Resource Allocation     0
Mental Fatigue Score    0
Burn Rate               0
dtype: int64

In [13]:
# 0 --- Female
# 1 --- Male
def gen(df):
    for i in range(len(df.iloc[:,1])):
        if df.iloc[i,1] == "Female":
            df.iloc[i,1] = int(0)
        elif df.iloc[i,1] == "Male":
            df.iloc[i,1] = int(1)

In [14]:
gen(df)

In [15]:
df

Date of Joining Gender Company Type WFH Setup Available  Designation  \
0          2008-09-30      0      Service                  No            2   
1          2008-11-30      1      Service                 Yes            1   
3          2008-11-03      1      Service                 Yes            1   
4          2008-07-24      0      Service                  No            3   
5          2008-11-26      1      Product                 Yes            2   
...               ...    ...          ...                 ...          ...   
22743      2008-12-15      0      Product                 Yes            1   
22744      2008-05-27      1      Product                  No            3   
22746      2008-01-19      0      Product                 Yes            3   
22748      2008-01-10      0      Service                  No            2   
22749      2008-01-06      1      Product                  No            3   

       Resource Allocation  Mental Fatigue Score  Burn Rate  
0                      3.0                   3.8       0.16  
1                      2.0                   5.0       0.36  
3                      1.0                   2.6       0.20  
4                      7.0                   6.9       0.52  
5                      4.0                   3.6       0.29  
...                    ...                   ...        ...  
22743                  3.0                   6.0       0.48  
22744                  7.0                   6.2       0.54  
22746                  6.0                   6.7       0.59  
22748                  5.0                   5.9       0.52  
22749                  6.0                   7.8       0.61  

[18590 rows x 8 columns]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18590 entries, 0 to 22749
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   Date of Joining       18590 non-null  datetime64[ns]
 1   Gender                18590 non-null  object        
 2   Company Type          18590 non-null  object        
 3   WFH Setup Available   18590 non-null  object        
 4   Designation           18590 non-null  int64         
 5   Resource Allocation   18590 non-null  float64       
 6   Mental Fatigue Score  18590 non-null  float64       
 7   Burn Rate             18590 non-null  float64       
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 1.3+ MB


In [17]:
for i in range(len(df.iloc[:,1])):
    df.iloc[i,1] = int(df.iloc[i,1])

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18590 entries, 0 to 22749
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   Date of Joining       18590 non-null  datetime64[ns]
 1   Gender                18590 non-null  object        
 2   Company Type          18590 non-null  object        
 3   WFH Setup Available   18590 non-null  object        
 4   Designation           18590 non-null  int64         
 5   Resource Allocation   18590 non-null  float64       
 6   Mental Fatigue Score  18590 non-null  float64       
 7   Burn Rate             18590 non-null  float64       
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 1.3+ MB


In [19]:
df.iloc[:,2].unique()

array(['Service', 'Product'], dtype=object)

In [20]:
def ct(df):
    for i in range(len(df.iloc[:,2])):
        if df.iloc[i,2] == "Service":
            df.iloc[i,2] = int(0)
        elif df.iloc[i,2] == "Product":
            df.iloc[i,2] = int(1)

In [21]:
ct(df)

In [22]:
df

Date of Joining Gender Company Type WFH Setup Available  Designation  \
0          2008-09-30      0            0                  No            2   
1          2008-11-30      1            0                 Yes            1   
3          2008-11-03      1            0                 Yes            1   
4          2008-07-24      0            0                  No            3   
5          2008-11-26      1            1                 Yes            2   
...               ...    ...          ...                 ...          ...   
22743      2008-12-15      0            1                 Yes            1   
22744      2008-05-27      1            1                  No            3   
22746      2008-01-19      0            1                 Yes            3   
22748      2008-01-10      0            0                  No            2   
22749      2008-01-06      1            1                  No            3   

       Resource Allocation  Mental Fatigue Score  Burn Rate  
0                      3.0                   3.8       0.16  
1                      2.0                   5.0       0.36  
3                      1.0                   2.6       0.20  
4                      7.0                   6.9       0.52  
5                      4.0                   3.6       0.29  
...                    ...                   ...        ...  
22743                  3.0                   6.0       0.48  
22744                  7.0                   6.2       0.54  
22746                  6.0                   6.7       0.59  
22748                  5.0                   5.9       0.52  
22749                  6.0                   7.8       0.61  

[18590 rows x 8 columns]

In [23]:
df.iloc[:,3].unique()

array(['No', 'Yes'], dtype=object)

In [24]:
def wfh(df):
    for i in range(len(df.iloc[:,3])):
        if df.iloc[i,3] == "No":
            df.iloc[i,3] = int(0)
        elif df.iloc[i,3] == "Yes":
            df.iloc[i,3] = int(1)

In [25]:
wfh(df)

In [26]:
df

Date of Joining Gender Company Type WFH Setup Available  Designation  \
0          2008-09-30      0            0                   0            2   
1          2008-11-30      1            0                   1            1   
3          2008-11-03      1            0                   1            1   
4          2008-07-24      0            0                   0            3   
5          2008-11-26      1            1                   1            2   
...               ...    ...          ...                 ...          ...   
22743      2008-12-15      0            1                   1            1   
22744      2008-05-27      1            1                   0            3   
22746      2008-01-19      0            1                   1            3   
22748      2008-01-10      0            0                   0            2   
22749      2008-01-06      1            1                   0            3   

       Resource Allocation  Mental Fatigue Score  Burn Rate  
0                      3.0                   3.8       0.16  
1                      2.0                   5.0       0.36  
3                      1.0                   2.6       0.20  
4                      7.0                   6.9       0.52  
5                      4.0                   3.6       0.29  
...                    ...                   ...        ...  
22743                  3.0                   6.0       0.48  
22744                  7.0                   6.2       0.54  
22746                  6.0                   6.7       0.59  
22748                  5.0                   5.9       0.52  
22749                  6.0                   7.8       0.61  

[18590 rows x 8 columns]

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18590 entries, 0 to 22749
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   Date of Joining       18590 non-null  datetime64[ns]
 1   Gender                18590 non-null  object        
 2   Company Type          18590 non-null  object        
 3   WFH Setup Available   18590 non-null  object        
 4   Designation           18590 non-null  int64         
 5   Resource Allocation   18590 non-null  float64       
 6   Mental Fatigue Score  18590 non-null  float64       
 7   Burn Rate             18590 non-null  float64       
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 1.3+ MB


In [28]:
df.iloc[:,0] = pd.to_datetime(df.iloc[:,0])

/var/folders/35/6f1p6jjn4k5_34j141ftg6v40000gn/T/ipykernel_9833/2205806744.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[:,0] = pd.to_datetime(df.iloc[:,0])


In [29]:
df["Year"] = df.iloc[:,0].dt.year

/var/folders/35/6f1p6jjn4k5_34j141ftg6v40000gn/T/ipykernel_9833/1455933347.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"] = df.iloc[:,0].dt.year


In [30]:
df["Month"] = df.iloc[:,0].dt.month

/var/folders/35/6f1p6jjn4k5_34j141ftg6v40000gn/T/ipykernel_9833/18447040.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Month"] = df.iloc[:,0].dt.month


In [31]:
df["Date"] = df.iloc[:,0].dt.day

/var/folders/35/6f1p6jjn4k5_34j141ftg6v40000gn/T/ipykernel_9833/94296409.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Date"] = df.iloc[:,0].dt.day


In [32]:
df

Date of Joining Gender Company Type WFH Setup Available  Designation  \
0          2008-09-30      0            0                   0            2   
1          2008-11-30      1            0                   1            1   
3          2008-11-03      1            0                   1            1   
4          2008-07-24      0            0                   0            3   
5          2008-11-26      1            1                   1            2   
...               ...    ...          ...                 ...          ...   
22743      2008-12-15      0            1                   1            1   
22744      2008-05-27      1            1                   0            3   
22746      2008-01-19      0            1                   1            3   
22748      2008-01-10      0            0                   0            2   
22749      2008-01-06      1            1                   0            3   

       Resource Allocation  Mental Fatigue Score  Burn Rate  Year  Month  Date  
0                      3.0                   3.8       0.16  2008      9    30  
1                      2.0                   5.0       0.36  2008     11    30  
3                      1.0                   2.6       0.20  2008     11     3  
4                      7.0                   6.9       0.52  2008      7    24  
5                      4.0                   3.6       0.29  2008     11    26  
...                    ...                   ...        ...   ...    ...   ...  
22743                  3.0                   6.0       0.48  2008     12    15  
22744                  7.0                   6.2       0.54  2008      5    27  
22746                  6.0                   6.7       0.59  2008      1    19  
22748                  5.0                   5.9       0.52  2008      1    10  
22749                  6.0                   7.8       0.61  2008      1     6  

[18590 rows x 11 columns]

In [33]:
df.drop(["Date of Joining"],axis = 1,inplace = True)

/var/folders/35/6f1p6jjn4k5_34j141ftg6v40000gn/T/ipykernel_9833/1547362959.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(["Date of Joining"],axis = 1,inplace = True)


In [34]:
df

Gender Company Type WFH Setup Available  Designation  \
0          0            0                   0            2   
1          1            0                   1            1   
3          1            0                   1            1   
4          0            0                   0            3   
5          1            1                   1            2   
...      ...          ...                 ...          ...   
22743      0            1                   1            1   
22744      1            1                   0            3   
22746      0            1                   1            3   
22748      0            0                   0            2   
22749      1            1                   0            3   

       Resource Allocation  Mental Fatigue Score  Burn Rate  Year  Month  Date  
0                      3.0                   3.8       0.16  2008      9    30  
1                      2.0                   5.0       0.36  2008     11    30  
3                      1.0                   2.6       0.20  2008     11     3  
4                      7.0                   6.9       0.52  2008      7    24  
5                      4.0                   3.6       0.29  2008     11    26  
...                    ...                   ...        ...   ...    ...   ...  
22743                  3.0                   6.0       0.48  2008     12    15  
22744                  7.0                   6.2       0.54  2008      5    27  
22746                  6.0                   6.7       0.59  2008      1    19  
22748                  5.0                   5.9       0.52  2008      1    10  
22749                  6.0                   7.8       0.61  2008      1     6  

[18590 rows x 10 columns]

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18590 entries, 0 to 22749
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Gender                18590 non-null  object 
 1   Company Type          18590 non-null  object 
 2   WFH Setup Available   18590 non-null  object 
 3   Designation           18590 non-null  int64  
 4   Resource Allocation   18590 non-null  float64
 5   Mental Fatigue Score  18590 non-null  float64
 6   Burn Rate             18590 non-null  float64
 7   Year                  18590 non-null  int64  
 8   Month                 18590 non-null  int64  
 9   Date                  18590 non-null  int64  
dtypes: float64(3), int64(4), object(3)
memory usage: 1.6+ MB


In [37]:
Y = df.iloc[:,6]

In [38]:
Y.info()

<class 'pandas.core.series.Series'>
Int64Index: 18590 entries, 0 to 22749
Series name: Burn Rate
Non-Null Count  Dtype  
--------------  -----  
18590 non-null  float64
dtypes: float64(1)
memory usage: 290.5 KB


In [39]:
df = df.drop(labels = ["Burn Rate"],axis = 1)

In [40]:
X = df

In [41]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18590 entries, 0 to 22749
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Gender                18590 non-null  object 
 1   Company Type          18590 non-null  object 
 2   WFH Setup Available   18590 non-null  object 
 3   Designation           18590 non-null  int64  
 4   Resource Allocation   18590 non-null  float64
 5   Mental Fatigue Score  18590 non-null  float64
 6   Year                  18590 non-null  int64  
 7   Month                 18590 non-null  int64  
 8   Date                  18590 non-null  int64  
dtypes: float64(2), int64(4), object(3)
memory usage: 1.4+ MB


In [42]:
train_x, test_x,train_y,test_y = train_test_split(X,Y,test_size=0.25)

In [43]:
from sklearn.linear_model import LinearRegression

In [44]:
lr = LinearRegression()

In [45]:
lr.fit(train_x,train_y)

LinearRegression()

In [46]:
y_hat = lr.predict(test_x)

In [47]:
lr.coef_

array([ 4.81814471e-03, -7.88854391e-05, -1.17829746e-02, -4.38414632e-03,
        2.82887714e-02,  7.38449374e-02,  1.73472348e-18, -1.01042837e-04,
       -5.14721555e-05])

In [48]:
lr.intercept_

-0.08307836528164403

In [49]:
y_hat

array([0.47161337, 0.68924554, 0.88194019, ..., 0.34596095, 0.59582083,
       0.86993888])

In [50]:
len(test_y)

4648

In [51]:
len(y_hat)

4648

In [52]:
lr.score(test_x,test_y)

0.9232428101092011

In [53]:
from sklearn.metrics import r2_score

In [54]:
r2_score(test_y, y_hat)

0.9232428101092011